const $=id=>document.getElementById(id);let csrf='',state={},screen='welcome',polling=false;
function show(id){screen=id;for(const s of ['welcome','import-panel','progress','complete'])$(s).hidden=s!==id}
function error(message){$('error').textContent=message;$('error').hidden=!message}
async function request(path,body){const r=await fetch(path,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json','X-Mutti-CSRF':csrf},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.status===204||r.status===202?null:r.json()}
async function discover(){try{const found=await request('/api/discover');$('found').replaceChildren();if(!found.length){$('found').textContent='Keinen eingerichteten Jellyfin-Server gefunden. Trage seine Adresse ein.';return}for(const s of found){const button=document.createElement('button');button.type='button';button.textContent=`${s.name} · ${s.version} · ${s.address}`;button.onclick=()=>{$('address').value=s.address};$('found').append(button)}if(!$('address').value)$('address').value=found[0].address}catch(e){$('found').textContent='Automatische Suche nicht verfügbar. Trage die Serveradresse ein.'}}
$('choose-import').onclick=()=>{error('');show('import-panel');discover()};$('back').onclick=()=>{error('');show('welcome')};
$('choose-new').onclick=async()=>{try{const result=await request('/api/new',{});location.assign(result.target)}catch(e){error(e.message)}};
$('add-mapping').onclick=()=>{const row=document.createElement('div');row.className='mapping';const old=document.createElement('input');old.placeholder='Bisheriger Pfad';old.setAttribute('aria-label','Bisheriger Medienpfad');const current=document.createElement('input');current.placeholder='Ordner auf diesem Rechner';current.setAttribute('aria-label','Neuer Medienpfad');const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent=window.webkit?.messageHandlers?.muttiFolder?'Auswählen':'Entfernen';button.onclick=async()=>{if(window.webkit?.messageHandlers?.muttiFolder){const path=await window.webkit.messageHandlers.muttiFolder.postMessage({});if(path)current.value=path}else row.remove()};row.append(old,current,button);$('mappings').append(row)};
$('import-form').onsubmit=async e=>{e.preventDefault();error('');const Mappings={};for(const row of $('mappings').children){const [a,b]=row.querySelectorAll('input');if(a.value&&b.value)Mappings[a.value]=b.value}try{await request('/api/import',{Address:$('address').value,Username:$('username').value,Password:$('password').value,TargetUsername:$('target-username').value,TargetPassword:$('target-password').value,Replace:$('replace').checked,Mappings});$('password').value='';$('target-password').value='';show('progress')}catch(e){error(e.message)}};
$('cancel').onclick=async()=>{try{await request('/api/cancel',{});$('cancel').disabled=true}catch(e){error(e.message)}};
function complete(report){show('complete');$('counts').replaceChildren();for(const [key,label] of [['Users','Benutzer'],['Libraries','Bibliotheken'],['Items','Medieneinträge'],['UserData','Wiedergabedaten']]){const card=document.createElement('span');const n=document.createElement('b');n.textContent=report[key]??0;card.append(n,document.createTextNode(label));$('counts').append(card)}$('notes').replaceChildren();for(const note of report.notes??[]){const li=document.createElement('li');li.textContent=note;$('notes').append(li)}$('open-library').href=state.target}
async function poll(){if(polling)return;polling=true;try{state=await request('/api/state');const busy=['checking','backup','importing','verifying','activating'].includes(state.phase);$('choose-new').disabled=!state.ready||busy;$('choose-import').disabled=!state.ready||busy;$('submit').disabled=!state.ready||busy;$('replace-fields').hidden=!state.setupComplete;$('choose-new').hidden=state.setupComplete;$('existing').hidden=!state.setupComplete;$('existing').href=state.target;if(busy){show('progress');$('progress-message').textContent=state.message;$('cancel').disabled=state.phase==='activating'}else if(state.phase==='complete'&&state.report){error('');complete(state.report)}else if(state.phase==='error'){error(state.message);if(screen==='progress')show('import-panel');$('cancel').disabled=false}}catch(e){error('Mutti ist gerade nicht erreichbar. Bitte die App erneut öffnen.')}finally{polling=false}}
(async()=>{try{csrf=(await request('/api/session')).csrf;if(location.hash==='#import'){show('import-panel');discover()}await poll();setInterval(poll,1200)}catch(e){error(e.message)}})();
