const $=id=>document.getElementById(id);let csrf='',state={},screen='welcome',polling=false,nativeOwner=false,submitting=false,lastStateAt=0,pollFailed=false;
const kurt=new window.MuttiKurt($('kurt'));
const nativeImport=window.webkit?.messageHandlers?.muttiImport;
function show(id){screen=id;kurt.setVisible(id==='progress');for(const s of ['welcome','import-panel','progress','complete'])$(s).hidden=s!==id}
function error(message){$('error').textContent=message;$('error').hidden=!message}
async function request(path,body){const r=await fetch(path,body===undefined?{cache:'no-store',signal:AbortSignal.timeout(8000)}:{method:'POST',headers:{'Content-Type':'application/json','X-Mutti-CSRF':csrf},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.status===204||r.status===202?null:r.json()}
async function discover(){try{const found=await request('/api/discover');$('found').replaceChildren();if(!found.length){$('found').textContent=t('Keinen eingerichteten Jellyfin-Server gefunden. Trage seine Adresse ein.');return}for(const s of found){const button=document.createElement('button');button.type='button';button.textContent=`${s.name} · ${s.version} · ${s.address}`;button.onclick=()=>{$('address').value=s.address};$('found').append(button)}if(!$('address').value)$('address').value=found[0].address}catch(e){$('found').textContent=t('Automatische Suche nicht verfügbar. Trage die Serveradresse ein.')}}
$('choose-import').onclick=()=>{error('');show('import-panel');discover()};$('back').onclick=()=>{error('');show('welcome')};
$('choose-new').onclick=async()=>{try{const result=await request('/api/new',{});location.assign(result.target)}catch(e){error(e.message)}};
$('add-mapping').onclick=()=>{const row=document.createElement('div');row.className='mapping';const old=document.createElement('input');old.placeholder=t('Bisheriger Pfad');old.setAttribute('aria-label',t('Bisheriger Medienpfad'));const current=document.createElement('input');current.placeholder=t('Ordner auf diesem Rechner');current.setAttribute('aria-label',t('Neuer Medienpfad'));const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent=t(window.webkit?.messageHandlers?.muttiFolder?'Auswählen':'Entfernen');button.onclick=async()=>{if(window.webkit?.messageHandlers?.muttiFolder){const path=await window.webkit.messageHandlers.muttiFolder.postMessage({});if(path)current.value=path}else row.remove()};row.append(old,current,button);$('mappings').append(row)};
$('import-form').onsubmit=async e=>{e.preventDefault();error('');const Mappings={};for(const row of $('mappings').children){const [a,b]=row.querySelectorAll('input');if(a.value&&b.value)Mappings[a.value]=b.value}if(submitting)return;submitting=true;$('submit').disabled=true;try{const input={PrepareSource:true,Address:$('address').value,Username:$('username').value,Password:$('password').value,TargetUsername:$('target-username').value,TargetPassword:$('target-password').value,Replace:nativeOwner?state.setupComplete:$('replace').checked,Mappings};if(nativeOwner){const result=await nativeImport.postMessage({action:'start',input});if(result.cancelled)return}else await request('/api/import',input);$('password').value='';$('target-password').value='';show('progress')}catch(e){error(e.message)}finally{submitting=false;await poll()}};
$('cancel').onclick=async()=>{try{await request('/api/cancel',{});$('cancel').disabled=true}catch(e){error(e.message)}};
function complete(report){show('complete');$('counts').replaceChildren();for(const [key,label] of [['Users','Benutzer'],['Libraries','Bibliotheken'],['Items','Medieneinträge'],['UserData','Wiedergabedaten']]){const card=document.createElement('span');const n=document.createElement('b');n.textContent=report[key]??0;card.append(n,document.createTextNode(t(label)));$('counts').append(card)}$('notes').replaceChildren();for(const note of report.notes??[]){const li=document.createElement('li');li.textContent=note;$('notes').append(li)}$('open-library').href=state.target+'#/mutti'}
const steps=['Zugang prüfen','Jellyfin sichern','Umzug vorbereiten','Daten übernehmen','Ergebnis prüfen','Quelle abgleichen','Mutti öffnen'];
function duration(seconds){seconds=Math.max(0,Math.floor(seconds));const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return h?t('{0} Std. {1} Min.',h,m):m?t('{0} Min. {1} Sek.',m,s):t('{0} Sek.',s)}
function byteSize(bytes){const units=['B','KiB','MiB','GiB'];let i=0;while(bytes>=1024&&i<3){bytes/=1024;i++}return `${bytes.toLocaleString(muttiLang==='en'?'en-GB':'de-DE',{maximumFractionDigits:i?1:0})} ${units[i]}`}
function progress(){
 if(screen!=='progress')return;
 kurt.setState({step:state.progress?.step||0,job:state.progress?.startedAt||'',connected:!pollFailed});
 const p=state.progress,age=lastStateAt?Math.floor((performance.now()-lastStateAt)/1000):0;
 $('progress-connection').textContent=lastStateAt?pollFailed?t('Verbindung zu Mutti unterbrochen. Letzte Rückmeldung vor {0} Der Vorgang kann weiterlaufen; die Anzeige versucht automatisch, sich wieder zu verbinden.',duration(age)):t('Status wird laufend aktualisiert · letzte Rückmeldung vor {0}',duration(age)):t('Status wird geladen …');
 if(!p?.step)return;
 $('progress-elapsed').textContent=duration(p.elapsedSeconds+(p.finishedAt?.startsWith('0001')?age:0));
 $('progress-step-time').textContent=duration(p.stepSeconds+(p.finishedAt?.startsWith('0001')?age:0));
 $('progress-measurement').textContent=p.measured?t('{0}: {1} · letzte messbare Änderung vor {2}',p.measurement,byteSize(p.bytes),duration(p.idleSeconds+age)):t('Für diesen Arbeitsschritt liegen noch keine messbaren Fortschrittsdaten vor.');
 const idle=p.idleSeconds+age,waiting=idle>=90&&!pollFailed;
 $('progress-wait').hidden=!waiting;
 const warning=waiting?t(p.measured?'Seit längerer Zeit ist keine weitere Dateiänderung messbar.':'Dieser Schritt liefert noch keine weiteren Fortschrittsdaten.')+t(' Jellyfin kann Daten zunächst intern verarbeiten. Ein Stillstand ist damit nicht sicher nachgewiesen. ')+t(p.step===2||p.step===6?'Wenn das anhält, bitte den Sicherungsstatus und die Protokolle auf Jellyfin prüfen.':'Wenn das anhält, bitte die Mutti-Protokolle prüfen.'):' ';
 if($('progress-wait').textContent!==warning)$('progress-wait').textContent=warning;
 if($('progress-steps').dataset.step!==String(p.step)){
  $('progress-steps').dataset.step=p.step;$('progress-steps').replaceChildren();
  steps.forEach((label,i)=>{const li=document.createElement('li');const number=document.createElement('span');number.className='step-number';number.textContent=i<p.step-1?'✓':String(i+1);number.setAttribute('aria-hidden','true');const name=document.createElement('span');name.textContent=t(label);li.append(number,name);li.className=i<p.step-1?'done':i===p.step-1?'current':'';if(i===p.step-1)li.setAttribute('aria-current','step');$('progress-steps').append(li)});
 }
}
setInterval(progress,1000);
async function poll(){if(polling)return;polling=true;try{state=await request('/api/state');lastStateAt=performance.now();pollFailed=false;const busy=['checking','backup','importing','verifying','activating','update'].includes(state.phase);$('choose-new').disabled=!state.ready||busy;$('choose-import').disabled=!state.ready||busy;$('submit').disabled=!state.ready||busy||submitting;$('replace-fields').hidden=!state.setupComplete;$('target-credentials').hidden=nativeOwner;$('replace-confirmation').hidden=nativeOwner;if(nativeOwner)$('replace-description').textContent=t('Den Wechsel bestätigst du direkt in der App. Danach verwendest du deinen bisherigen Jellyfin-Zugang weiter.');$('choose-new').hidden=state.setupComplete;$('existing').hidden=!state.setupComplete;$('existing').href=state.target+'#/mutti';if(busy){show('progress');if($('progress-message').textContent!==state.message)$('progress-message').textContent=state.message;progress();$('cancel').disabled=state.phase==='activating'||state.phase==='update'}else if(state.phase==='complete'&&state.report){error('');complete(state.report)}else if(state.phase==='error'||state.phase==='update_blocked'){error(state.message);if(screen==='progress')show('import-panel');$('cancel').disabled=false}else if(state.serviceMessage){error(state.serviceMessage)}else if(state.ready&&!busy){error('')}}catch(e){pollFailed=true;if(screen==='progress')progress();else error(t('Mutti ist gerade nicht erreichbar. Die Verbindung wird automatisch erneut versucht.'))}finally{polling=false}}
(async()=>{try{csrf=(await request('/api/session')).csrf;if(nativeImport)nativeOwner=await nativeImport.postMessage({action:'available'});if(location.hash==='#import'){show('import-panel');discover()}await poll();setInterval(poll,1200)}catch(e){error(e.message)}})();
